# Generated by Django 4.2.16 on 2026-01-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("usage_limit", models.PositiveIntegerField()),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="email_contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Email Name", max_length=100)),
                (
                    "email",
                    models.CharField(
                        default="admin@jakartaurologymedicalupdate.id",
                        help_text="contoh@gmail.com",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageForPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Workshop", "Workshop"),
                            ("Seminar", "Seminar"),
                            ("Scicom", "Scicom"),
                        ],
                        default="Seminar",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_method", models.TextField(default="Sample Description")),
            ],
        ),
        migrations.CreateModel(
            name="qrcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        default="https://www.example.com",
                        help_text="Enter a valid URL starting with http:// or https://",
                    ),
                ),
                ("image", models.ImageField(upload_to="qrcode/")),
            ],
        ),
        migrations.CreateModel(
            name="scicom_rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.TextField(default="Sample Description")),
                (
                    "rule_description",
                    models.TextField(
                        blank=True, default="Sample Description", null=True
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="scicom_pdfs/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seminar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(default="Sample Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seminar_images/"
                    ),
                ),
                ("date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, default="RSCM", max_length=200, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Seminar", "Seminar"), ("Workshop", "Workshop")],
                        default="Seminar",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="seminars_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_section_one", models.TextField(default="Sample Description")),
                ("text_section_two", models.TextField(default="Sample Description")),
                (
                    "flyer_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seminars_page/"
                    ),
                ),
                (
                    "at_a_glance_text",
                    models.TextField(blank=True, default="Sample Description"),
                ),
                (
                    "at_a_glance_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seminars_page/"
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True, default="Sample Description", max_length=200
                    ),
                ),
                (
                    "venue_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seminars_page/"
                    ),
                ),
                ("venue_booking_link", models.URLField(blank=True, null=True)),
                (
                    "register_seminar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symposium_register_pages",
                        to="tickets.seminar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="Sample Description")),
                ("image", models.ImageField(upload_to="sponsor_images/")),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="sponsor_banner_images/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Large", "Large"),
                            ("Medium", "Medium"),
                            ("Small", "Small"),
                        ],
                        default="Small",
                        max_length=8,
                    ),
                ),
                (
                    "youtube_video_id",
                    models.CharField(
                        blank=True,
                        help_text="YouTube video ID for the sponsor",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WelcomingSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="Sample Description")),
                ("image", models.ImageField(upload_to="about_us/")),
                ("name", models.TextField(default="Sample Description")),
                ("speech", models.TextField(default="Sample Description")),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Contact Name", max_length=100)),
                (
                    "number",
                    models.CharField(
                        default="62812345678",
                        help_text="+62812345678 tanpa +",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="workshops_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_section_one", models.TextField(default="Sample Description")),
                ("text_section_two", models.TextField(default="Sample Description")),
            ],
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="umum", max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("available_seats", models.IntegerField(default=1)),
                ("reserved_seats", models.IntegerField(default=0)),
                ("booked_seats", models.IntegerField(default=0)),
                (
                    "seminar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_categories",
                        to="tickets.seminar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attendee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_image",
                    models.ImageField(blank=True, null=True, upload_to="tickets/qr/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="tickets.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SymposiumFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="seminars_page/faculties/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "symposium_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="tickets.seminars_page",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SciComSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(default="Jakarta, Indonesia")),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("Urologist", "Urologist"),
                            ("Resident", "Resident"),
                            ("General Practitioner", "General Practitioner"),
                            ("Medical Student", "Medical Student"),
                        ],
                        default="Urologist",
                        max_length=20,
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("abstract", "Paper Abstract"),
                            ("video", "Educative Video"),
                            ("flyer", "Educative Flyer"),
                        ],
                        default="abstract",
                        max_length=10,
                    ),
                ),
                (
                    "abstract_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "paper_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Case Report", "Case Report"),
                            ("Primary Study", "Primary Study"),
                            ("Secondary Study", "Secondary Study"),
                            ("Systematic Review", "Systematic Review"),
                            ("Meta Analysis", "Meta Analysis"),
                        ],
                        help_text="Only valid for Abstract submission",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "abstract_authors",
                    models.TextField(
                        blank=True,
                        help_text="List authors separated by commas",
                        null=True,
                    ),
                ),
                ("abstract_text", models.TextField(blank=True, null=True)),
                (
                    "link_abstract",
                    models.URLField(
                        blank=True,
                        help_text="Link to the full abstract or PDF (Google Drive, etc.)",
                        null=True,
                    ),
                ),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "video_authors",
                    models.TextField(
                        blank=True,
                        help_text="List authors separated by commas",
                        null=True,
                    ),
                ),
                ("link_video", models.URLField(blank=True, null=True)),
                (
                    "flyer_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "flyer_authors",
                    models.TextField(
                        blank=True,
                        help_text="List authors separated by commas",
                        null=True,
                    ),
                ),
                ("link_flyer", models.URLField(blank=True, null=True)),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Tick to mark this abstract as accepted.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proof", models.ImageField(upload_to="payment_proofs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price_paid",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=12),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ticket_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.ticketcategory"
            ),
        ),
        migrations.CreateModel(
            name="landing_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_section_one", models.TextField(default="Sample Description")),
                ("text_section_one", models.TextField(default="Sample Description")),
                (
                    "image_section_one",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                (
                    "header_section_two",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                ("text_section_two", models.TextField(default="Sample Description")),
                (
                    "image_section_two_left",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                (
                    "image_section_two_header_left",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "image_section_two_text_left",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "image_section_two_right",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                (
                    "image_section_two_header_right",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "image_section_two_text_right",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "header_section_three",
                    models.TextField(default="Sample Description"),
                ),
                ("text_section_three", models.TextField(default="Sample Description")),
                (
                    "image_section_three_left",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                (
                    "image_section_three_right",
                    models.ImageField(upload_to="landingpage_images/"),
                ),
                ("sponsor", models.ManyToManyField(blank=True, to="tickets.sponsor")),
                (
                    "welcoming",
                    models.ManyToManyField(blank=True, to="tickets.welcomingspeech"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.cart"
                    ),
                ),
                (
                    "ticket_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptedAbstractSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ppt_link",
                    models.URLField(
                        blank=True, help_text="Link to the PowerPoint presentation"
                    ),
                ),
                (
                    "poster_link",
                    models.URLField(blank=True, help_text="Link to the E-Poster"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "abstract",
                    models.ForeignKey(
                        limit_choices_to={"submission_type": "abstract"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.scicomsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="about_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_section_one", models.TextField(default="Sample Description")),
                (
                    "header_section_two",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "subheader_section_two_left",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "text_section_two_left",
                    models.TextField(default="Sample Description"),
                ),
                (
                    "subheader_section_two_right",
                    models.CharField(default="Sample Description", max_length=100),
                ),
                (
                    "text_section_two_right",
                    models.TextField(default="Sample Description"),
                ),
                (
                    "image_section_two_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us_images/"
                    ),
                ),
                (
                    "image_section_two_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us_images/"
                    ),
                ),
                (
                    "image_section_two_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us_images/"
                    ),
                ),
                (
                    "image_section_two_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us_images/"
                    ),
                ),
                (
                    "image_section_two_5",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us_images/"
                    ),
                ),
                (
                    "email_contact",
                    models.ManyToManyField(blank=True, to="tickets.email_contact"),
                ),
                (
                    "whatsapp_numbers",
                    models.ManyToManyField(blank=True, to="tickets.whatsappnumber"),
                ),
            ],
        ),
    ]
