# Generated by Django 4.2.16 on 2026-06-22 15:28

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scicomsettings",
            name="new_submission_deadline",
            field=models.DateTimeField(
                default=tickets.models.default_scicom_new_submission_deadline,
                help_text="Deadline for accepting new Scientific Competition submissions.",
                verbose_name="New submission deadline",
            ),
        ),
        migrations.AddField(
            model_name="scicomsettings",
            name="presentation_submission_deadline",
            field=models.DateTimeField(
                default=tickets.models.default_scicom_presentation_submission_deadline,
                help_text="Deadline for accepting presentation materials from accepted abstracts.",
                verbose_name="Presentation submission deadline",
            ),
        ),
    ]
